### `Problem-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
import numpy as np

In [14]:
# code here
a = np.random.randint(0,100,12).reshape(3,4)
a

array([[48, 88, 11, 19],
       [38,  0, 76, 49],
       [49, 35, 85, 25]])

In [15]:
# (i)Sort this matrix. np.sort()

np.sort(a)

array([[11, 19, 48, 88],
       [ 0, 38, 49, 76],
       [25, 35, 49, 85]])

In [16]:
# (ii)Sort this matrix based on values in 2nd column.


a[a[:, 1].argsort()]

array([[38,  0, 76, 49],
       [49, 35, 85, 25],
       [48, 88, 11, 19]])

In [26]:
a

array([[48, 88, 11, 19],
       [38,  0, 76, 49],
       [49, 35, 85, 25]])

In [25]:
# (iii)Sort this matrix based on max value in each row.
def max_sort(row):
	return max(row)

a.sort(key = max_sort, reverse = True)


TypeError: sort() got an unexpected keyword argument 'key'

In [24]:
# Python3 code to demonstrate working of
# Sort Matrix by Maximum Row element
# Using sort() + max()

def max_sort(row):
	return max(row)

# initializing list
test_list = [[92,90,74],[6,63, 93],[15, 93, 96],[70, 60, 48]]

# printing original list
print("The original list is : " + str(test_list))

# sort() for sorting, max to get maximum values
test_list.sort(key = max_sort, reverse = True)

# printing result
print("The maximum sorted Matrix : " + str(test_list))


The original list is : [[92, 90, 74], [6, 63, 93], [15, 93, 96], [70, 60, 48]]
The maximum sorted Matrix : [[15, 93, 96], [6, 63, 93], [92, 90, 74], [70, 60, 48]]


In [21]:
# (iv) Sort based on elements value

aa = np.sort(a, axis=0)
aa = np.sort(aa, axis=1)
aa

array([[ 0, 11, 19, 38],
       [25, 35, 48, 76],
       [49, 49, 85, 88]])

### `Problem-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

In [28]:
# code here
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

np.r_[ ... ] and np.c_[ ... ] are useful alternatives to vstack and hstack, with square brackets [] instead of round ().

In [30]:
# (i) Add marks every student of an extra subject in the same array
extra_subject = [41, 87, 72, 36, 92]

marks = np.c_[marks, extra_subject]
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [32]:
# (ii) Add two new students marks in respective 5 subjects.(one subject added in above task)
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]

marks = np.r_[marks, [rec1,rec2]]
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [33]:
# (iii) Add extra column with sum of all subjects(5-subjects) marks

total_marks = np.sum(marks, axis=1)

marks = np.c_[marks, total_marks]
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [37]:
# (iv) Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows

m = marks[marks[:, 5].argsort()[::-1]]
m

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

### `Problem-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [38]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [39]:
uniqueRows = np.unique(arr, axis=0)
uniqueRows

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [40]:
uniqueCols = np.unique(arr, axis=1)
uniqueCols

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

### `Problem-4:` Flip given 2-D array along both axes at the same time.

```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
```
Flipped->
[[-1  8 -2 14 19 10]
 [ 7 11  2  1  6  0]
 [ 1  1  3  3  2  1]
 [ 8  8  8  3  2  1]
 [ 8  8  2  1  9  0]
 [ 1  1  3  3  2  1]]
```

In [41]:
# code here

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [46]:
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Problem-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [64]:
# code here
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])

In [65]:
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [66]:
arr[arr > 6]

array([10, 30,  9,  7])

In [68]:
arr[np.where(arr>6)]


array([10, 30,  9,  7])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [69]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [70]:
arr_2d = np.concatenate([arr1, arr2, arr3])
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


### `Problem-6:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [71]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [72]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [78]:
min = np.argmin(arr)
np.delete(arr, min)

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [79]:
max = np.argmax(arr)
np.delete(arr, max)

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

### `Problem-7:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [80]:
# code here

a = np.random.randint(100,700,24)
a

array([505, 381, 689, 427, 478, 573, 483, 394, 401, 223, 644, 249, 392,
       454, 524, 282, 632, 300, 646, 249, 574, 157, 411, 133])

In [84]:
a = np.clip(a,a_min=100,a_max=200)
a

array([133, 157, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [83]:
a = np.sort(a)
a

array([133, 157, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [85]:
np.cumsum(a)

array([ 133,  290,  490,  690,  890, 1090, 1290, 1490, 1690, 1890, 2090,
       2290, 2490, 2690, 2890, 3090, 3290, 3490, 3690, 3890, 4090, 4290,
       4490, 4690])

### `Problem-8:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [87]:
# code here
a = np.random.uniform(0, 1, size=20)
a

array([0.38194531, 0.6004883 , 0.91105984, 0.29858493, 0.86611502,
       0.3369211 , 0.73812566, 0.89495347, 0.19867868, 0.11498323,
       0.42979021, 0.344658  , 0.74676641, 0.93358655, 0.98002885,
       0.38668115, 0.00615072, 0.97140135, 0.99294496, 0.16076545])

In [90]:
a = np.round(a, 3)
a

array([0.382, 0.6  , 0.911, 0.299, 0.866, 0.337, 0.738, 0.895, 0.199,
       0.115, 0.43 , 0.345, 0.747, 0.934, 0.98 , 0.387, 0.006, 0.971,
       0.993, 0.161])

In [91]:
np.percentile(a,0)

0.006

In [92]:
np.percentile(a,100)

0.993

In [93]:
x = np.percentile(a,50)
y = np.percentile(a,51)
z = y-x
z

0.032299999999999884